# number of replicas
# by default 1
# replicaCount: 1

# image name
image: registry

# image tag  
imageTag: 2.6

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
imagePullPolicy: IfNotPresent

# registry port
port: 5000

# registry PVC storage size
storageSize: 20Gi

mainChart: codefresh