---
apiVersion: v1
kind: Secret
metadata:
  name: codefresh-registry
  labels:
    {{ include "codefresh-gitops.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "codefresh-gitops.imagePullSecret" . }}
