apiVersion: v1
description: Codefresh tls sign
name: cf-tls-sign
version: 0.1.0
keywords:
- codefresh
- kubernetes
- cf-tls-sign
home: https://codefresh.io/
icon: https://avatars1.githubusercontent.com/u/11412079?v=3
sources:
- https://github.com/codefresh-io/cf-tls-sign
maintainers:
- name: Alexei Ledenev
  email: alexei@codefresh.io
