{{- $registryService := printf "%s-%s.%s.svc:%v" .Release.Name .Values.global.registryService .Release.Namespace .Values.global.registryPort }}

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  serviceName: {{ template "fullname" . }}
  replicas: {{ default 2 .Values.replicaCount }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/builder-cm.yaml") . | sha256sum }}
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "register-dind-container",
            "image": "alexeiled/curl:3.6",
            "imagePullPolicy": "{{ default "" .Values.imagePullPolicy }}",
            "volumeMounts": [
              {
                "name": "builder-config",
                "mountPath": "/opt/dind/register",
                "subPath": "register"
              }
            ],
            "env": [
              {
                "name": "POD_NAME",
                "valueFrom": { "fieldRef": { "apiVersion": "v1", "fieldPath": "metadata.name" } }
              }
            ],
            "command": ["/bin/sh", "-c", "chmod +x /opt/dind/register && /opt/dind/register ${POD_NAME} {{ template "fullname" . }}.{{ .Release.Namespace}}.svc"]
          }
        ]'
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        release: {{ .Release.Name  | quote }}
        heritage: {{ .Release.Service  | quote }}
    spec:
      containers:
      - image: {{ .Values.global.dindImage | quote }}
        name:  {{ template "fullname" . }}
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        resources:
          limits:
            cpu: {{ .Values.global.dindCPULimits }}
            memory: {{ .Values.global.dindMemoryLimits }}
          requests:
            cpu: {{ .Values.global.dindCPU }}
            memory: {{ .Values.global.dindMemory }}
        securityContext:
          privileged: true
        ports:
        - containerPort: {{ .Values.containerPort }}
          protocol: TCP
        env:
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: {{ .Values.global.tlsRejectUnauthorized | quote }}
        - name: RUNTIME_LOCAL_REGISTRY_NAME
          value: {{ $registryService | quote }}
        command:
          - "/bin/sh"
          - "-c"
          - |
            rm -fv /var/run/docker.pid
            mkdir /var/run/codefresh
            mkdir -p /etc/docker/certs.d/$(RUNTIME_LOCAL_REGISTRY_NAME)/
            cp /etc/ssl/cf/ca.pem /etc/docker/certs.d/$(RUNTIME_LOCAL_REGISTRY_NAME)/ca.crt
            dockerd
        volumeMounts:
        - mountPath: /etc/ssl/cf
          readOnly: true
          name: cf-certs
        - mountPath: /etc/docker/daemon.json
          name: builder-config
          readOnly: true
          subPath: daemon.json
      volumes:
      - name: cf-certs
        secret:
          secretName: "{{ .Release.Name }}-{{ .Values.global.codefresh }}-cf-certs"
      - name: builder-config
        configMap:
          name: {{ template "fullname" . }}

