# number of replicas
# NOTE: cannot run more that 1 replica on single node cluster, like minikube
# by default 1
# replicaCount: 1

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
imagePullPolicy: IfNotPresent
redeploy: false

# Service type (ClusterIP, NodePort, LoadBalancer)
#service:
#  type: ClusterIP

# dind container port (1300 - default)
containerPort: 1300
