imagePullPolicy: Always

# Number of replicas
replicaCount: 1
redeploy: false

image: r.cfcr.io/codefresh-inc/codefresh/pipeline-manager
imageTag: master

# Service port
port: 9000

# Pod (target) port
targetPort: 9000

# service database name
mongodbName: pipeline-manager

mongoCreateDbJobScript: files/mongoCreateDbJobScript
