apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.org/redirect-to-https: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
          more_set_headers "X-Request-ID: $request_id";
          proxy_set_header X-Request-ID $request_id;
  name: {{ template "fullname" . }}-ingress
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service  | quote }}
spec:
  tls:
    - hosts:
      - '{{ .Values.ingress.domain }}'
      {{- if .Values.webTLS }}
      secretName: {{ template "fullname" . }}-{{ .Values.webTLS.secretName }}
      {{- else }}
      secretName: {{ template "fullname" . }}-star-selfsigned
      {{- end }}
  backend:
    serviceName: {{ .Release.Name }}-cfui
    servicePort: {{ .Values.servicePort }}
  rules:
  - http:
      paths:
      - path: /api/
        backend:
          serviceName: {{ .Release.Name }}-cfapi
          servicePort: {{ .Values.servicePort }}
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-cfui
          servicePort: {{ .Values.servicePort }}
