imagePullPolicy: Always

# Number of replicas
replicaCount: 1

image: codefresh/cluster-providers
imageTag: master

# Service port
port: 9000

# Pod (target) port
targetPort: 9000

# Secrets, should be replaced with env specific values
client-id: ""
client-secret: ""
safe-secret: ""

# Custom mongodb uri, set this if you don't want to use Chart's mongoDB instance
mongoURI: ""

