# Ebable RBAC for K8s cluster
# Requires Kubernetes 1.6.4+
# rbacEnable: true

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
imagePullPolicy: IfNotPresent

# customize consul chart
consul:
  Memory: 256Mi

# overrride mongodb chart values
mongo:
  # chart name
  nameOverride: mongodb
  # image to use
  image: bitnami/mongodb:3.4.5-r0

# use mongodb service name; should be same as mongo.nameOverride
cfapi:
  mongoService: mongodb
  mongoImage: bitnami/mongodb:3.4.5-r0
