# Ebable RBAC for K8s cluster
# Requires Kubernetes 1.6.4+
# rbacEnable: true

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
imagePullPolicy: IfNotPresent

# default application protocol
appProtocol: http

# default service port
servicePort: 80

# image with kubectl that can work with our K8s version
kubectlImage: lachlanevenson/k8s-kubectl:v1.6.4

# CFCR domain
# cfcrDomain: staging.cfcr.io (default)

# Segment black list
# segmentBlackList: "" by default

# OAuth router callback
# oauthRouterCallback: http://codefresh-inc-3.cf-cd.com:2222/api/auth/github/callback/ (default)

# GCE project
# gceProject: savvy-badge-103912 (default == staging)


# override mongodb chart values
mongodb:
  # image to use
  image: bitnami/mongodb:3.4.5-r0

# use mongodb service name; should be same as mongo.nameOverride
cfapi:
  mongodbImage: bitnami/mongodb:3.4.5-r0


# internal ingress controller; disable by default
ingress:
  enabled: false

dindImage: docker:17.05-dind

#======================= 
# GLOBAL settings
#=======================
global:
  # application url root
  appUrl: codefresh.dev

  # dind image with tag
  dindImage: docker:17.05-dind
  # dind cpu requests
  dindCPU: 500M
  # dind memory requests
  dindMemory: 256Mi
  # dind cpu limits
  dindCPULimits: 1500M
  # dind memory limits
  dindMemoryLimits: 4096Mi

  #----
  # Names and ports for commomn services

  # nats service
  natsService: nats
  natsPort: 4222

  # rabbitmq service name
  rabbitService: rabbitmq

  # mongodb service
  mongoService: mongodb
  mongoPort: 27017
  mongoDatabase: codefresh