# Ebable RBAC for K8s cluster
# Requires Kubernetes 1.6.4+
# rbacEnable: true

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
imagePullPolicy: IfNotPresent

# Codefresh APP URL
appUrl: codefresh.dev 

# default application protocol
appProtocol: http

# default service port
servicePort: 80

# image with kubectl that can work with our K8s version
kubectlImage: lachlanevenson/k8s-kubectl:v1.6.4

# customize consul chart
consul:
  Replicas: 1
  Memory: 256Mi

# override mongodb chart values
mongodb:
  # image to use
  image: bitnami/mongodb:3.4.5-r0

# use mongodb service name; should be same as mongo.nameOverride
cfapi:
  mongodbImage: bitnami/mongodb:3.4.5-r0

# use smaller registry storage
registry:
  storageSize: 8Gi

# runner configuration
runner:
  appUrl: codefresh.dev  

# internal ingress controller; disable by default
ingress:
  enabled: false