imagePullPolicy: Always
redeploy: false

# Number of replicas
replicaCount: 1

image: r.cfcr.io/codefresh-inc/codefresh/multiple-clusters
imageTag: master

# Service port
port: 9000

# Pod (target) port
targetPort: 9000

