# kind: scheduler-kubernetes
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
    version: {{ .Values.imageTag | quote }}
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        release: {{ .Release.Name  | quote }}
        heritage: {{ .Release.Service  | quote }}
        version: {{ .Values.imageTag | quote }}
    spec:
      imagePullSecrets:
        - name: "{{ .Release.Name }}-{{ .Values.global.codefresh }}-registry"
      terminationGracePeriodSeconds: 40
      containers:
      - name: {{ template "fullname" . }}
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        env:
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        - name: API_SAFE_SECRET
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.global.codefresh }}"
              key: api-safe-secret
        - name: BITBUCKET_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.global.codefresh }}"
              key: bitbucket-client-id
        - name: BITBUCKET_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.global.codefresh }}"
              key: bitbucket-client-secret
        - name: BL_USERS
          valueFrom:
            configMapKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.global.codefresh }}" 
              key: segment-blacklist-users
        - name: CF_HOST_NAME
          value: {{ .Values.global.appUrl | quote }}
        - name: CF_REGISTRY_ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.global.codefresh }}"
              key: registry-admin-token
        - name: CF_REGISTRY_API_KEY
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.global.codefresh }}"
              key: reg-auth-api-key
        - name: CF_REGISTRY_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.global.codefresh }}"
              key: cfcr-domain
        - name: CONSUL_HOST
          value: "{{ .Release.Name }}-{{ .Values.global.consulService }}.{{ .Release.Namespace }}"
        - name: EXTERNAL_URL
          value: "{{ .Values.global.appProtocol }}://{{ .Values.global.appUrl }}"
        - name: FIREBASE_SECRET
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.global.codefresh }}"
              key: firebase-secret
        - name: FIREBASE_URL
          valueFrom:
            configMapKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.global.codefresh }}"
              key: firebase-url
        - name: INTERNAL_USE_GITHUB_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.global.codefresh }}"
              key: github-internal-token
        - name: INTERNAL_SERVER_PORT
          value: {{ .Values.targetInternalPort | quote }}
        - name: GITHUB_API_HOST
          value: {{ .Values.github.apiHost | quote }}
        - name: GITHUB_API_PATH_PREFIX
          value: {{ .Values.github.apiPathPrefix | quote }}
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.global.codefresh }}"
              key: github-client-id
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.global.codefresh }}"
              key: github-client-secret
        - name: GITHUB_LOGIN_HOST
          value: {{ .Values.github.loginHost | quote }}
        - name: GITHUB_PROTOCOL
          value: {{ .Values.github.protocol | quote }}
        - name: GITLAB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.global.codefresh }}"
              key: gitlab-client-id
        - name: GITLAB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.global.codefresh }}"
              key: gitlab-client-secret
        - name: GITLAB_LOGIN_HOST
          value: {{ .Values.gitlab.loginHost | quote }}
        - name: GITLAB_PROTOCOL
          value: {{ .Values.gitlab.protocol | quote }}
        - name: GOOGLE_COMPUTE_ENGINE_PROJECT
          valueFrom:
            configMapKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.global.codefresh }}"
              key: google-compute-engine-project
        - name: LOGGLY_TOKEN
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.global.codefresh }}"
              key: loggly-token
        - name: MONGO_URI
          value: "mongodb://{{ .Values.global.mongodbUsername }}:{{ .Values.global.mongodbPassword }}@{{ .Release.Name }}-{{ .Values.global.mongoService }}.{{ .Release.Namespace }}:{{ .Values.global.mongoPort }}/{{ .Values.global.mongodbDatabase }}"
        - name: NEWRELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.global.codefresh }}"
              key: newrelic-license-key
        - name: PAYMENTS_SERVICE
          value: {{ .Values.global.paymentsService }}
        - name: PAYMENTS_URI
          value: http://$(PAYMENTS_SERVICE)
        - name: PORT
          value: {{ .Values.port | quote }}
        - name: POSTGRES_DATABASE
          value: {{ .Values.global.postgresDatabase }}
        - name: POSTGRES_HOST
          value: "{{ .Release.Name }}-{{ .Values.global.postgresService }}.{{ .Release.Namespace }}" 
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.global.codefresh }}"
              key: postgres-password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.global.codefresh }}"
              key: postgres-user
        - name: PROTOCOL
          value: {{ .Values.global.appProtocol | quote }}
        - name: RABBIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.global.codefresh }}"
              key: rabbitmq-password
        - name: RABBIT_USER
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.global.codefresh }}"
              key: rabbitmq-username
        - name: RABBIT_URL
          value: "amqp://$(RABBIT_USER):$(RABBIT_PASSWORD)@{{ .Release.Name }}-{{ .Values.global.rabbitService }}.{{ .Release.Namespace }}"
        - name: REDIS_URL
          value: "{{ .Release.Name }}-{{ .Values.global.redisService }}.{{ .Release.Namespace }}" 
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.global.codefresh }}"
              key: redis-password
        - name: QUEUE_SERVERS
          value: "nats://{{ .Release.Name }}-{{ .Values.global.natsService }}.{{ .Release.Namespace }}:{{ .Values.global.natsPort }}"
        - name: SLACK_APP_ID
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.global.codefresh }}"
              key: slack-app-id
        - name: SLACK_APP_SECRET
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.global.codefresh }}"
              key: slack-app-secret
        - name: SLACK_INTERNAL
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.global.codefresh }}"
              key: slack-internal
        - name: SEGMENT_ACTIVE
          value: {{ .Values.segmentEnable | quote }}
        - name: SEGMENT_KEY
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.global.codefresh }}"
              key: segment-key
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.global.codefresh }}"
              key: stripe-secret-key
        - name: TLS_SIGN_CLIENT_KEY
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-{{ .Values.global.codefresh }}"
              key: tls-client-key 
        #- name: OAUTH_ROUTER_CALLBACK
        #  valueFrom:
        #    configMapKeyRef:
        #      name: "{{ .Release.Name }}-{{ .Values.global.codefresh }}"
        #      key: oauth-router-callback
        ports:
        - containerPort: {{ .Values.port }}
          protocol: TCP
        - containerPort: {{ .Values.targetInternalPort }}
          protocol: TCP
        #readinessProbe:
        #  httpGet:
        #    path: /api/ping
        #    port: {{ .Values.port }}
        #  periodSeconds: 5
        #  timeoutSeconds: 5
        #  successThreshold: 1
        #  failureThreshold: 5
        volumeMounts:
        - name: config
          mountPath: /etc/admin/providers.json
          subPath: providers.json
        - name: config
          mountPath: /etc/admin/accounts.json
          subPath: accounts.json
        - name: config
          mountPath: /etc/admin/users.json
          subPath: users.json
        - mountPath: /etc/admin/hosts.added
          name: etc-hosts
          subPath: hosts-app
        - name: runtime-environments
          mountPath: /etc/admin/runtimeEnvironments.json
          subPath: runtimeEnvironments.json
        - name: node-clusters
          mountPath: /root/.kube/config
          subPath: kube-config
        - mountPath: /etc/ssl/cf/
          readOnly: true
          name: cf-certs-client
      volumes:
      - name: config
        configMap:
          name: {{ template "fullname" . }}
      - name: etc-hosts
        configMap:
          name: "{{ .Release.Name }}-{{ .Values.global.codefresh }}-etc-hosts"
      - name: runtime-environments
        configMap:
          name: "{{ .Release.Name }}-{{ .Values.global.codefresh }}-runtime-envs"
      - name: node-clusters
        secret:
          secretName: "{{ .Release.Name }}-{{ .Values.global.codefresh }}-node-clusters"
      - name: cf-certs-client
        secret:
          secretName: "{{ .Release.Name }}-{{ .Values.global.codefresh }}-certs-client"
      restartPolicy: Always