apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}-seed-mongo
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
spec:
  template:
    metadata:
      name: {{ template "fullname" . }}-seed-mongo
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        release: {{ .Release.Name  | quote }}
        heritage: {{ .Release.Service  | quote }}
    spec:
      containers:
      - name: {{ template "fullname" . }}-admin-account
        image: {{ .Values.mongodbImage }}
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "mongoimport --host {{ .Release.Name }}-{{ .Values.global.mongoService }}:{{ .Values.global.mongoPort }} --db {{ .Values.global.mongodbDatabase }} --username {{ .Values.global.mongodbUsername }} --password {{ .Values.global.mongodbPassword }} --collection accounts --type json --file /etc/admin/accounts.json"]
        volumeMounts:
        - name: seed
          mountPath: "/etc/admin/accounts.json"
          subPath: "accounts.json"
      - name: {{ template "fullname" . }}-admin-user
        image: {{ .Values.mongodbImage }}
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "mongoimport --host {{ .Release.Name }}-{{ .Values.global.mongoService }}:{{ .Values.global.mongoPort }} --db {{ .Values.global.mongodbDatabase }} --username  {{ .Values.global.mongodbUsername }} --password {{ .Values.global.mongodbPassword }} --collection users --type json --file /etc/admin/users.json"]
        volumeMounts:
        - name: seed
          mountPath: "/etc/admin/users.json"
          subPath: "users.json"
      restartPolicy: OnFailure
      volumes:
      - name: seed
        configMap:
          name: {{ template "fullname" . }}
