apiVersion: v1
kind: Secret
metadata:
    name: {{ template "fullname" . }}
    labels:
      app: {{ template "fullname" . }}
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: "{{ .Release.Name }}"
      heritage: "{{ .Release.Service }}"
type: Opaque
data:
    # GitHub secrets
    github-client-id: {{ default "" .Values.global.githubClientID | b64enc | quote }}  
    github-client-secret: {{ default "" .Values.global.githubClientSecret | b64enc | quote }} 
    github-internal-token: {{ default "" .Values.global.githubInternalToken | b64enc | quote }}

    # GitLab secrets
    gitlab-client-id: {{ default "" .Values.global.gitlabClientID | b64enc | quote }}
    gitlab-client-secret: {{ default "" .Values.global.gitlabClientSecret | b64enc | quote }}

    # Bitbucket secrets
    bitbucket-client-id: {{ default "" .Values.global.bitbucketClientID | b64enc | quote }}
    bitbucket-client-secret: {{ default "" .Values.global.bitbucketClientSecret | b64enc | quote }}
 