imagePullPolicy: Always
redeploy: false

# Number of replicas
replicaCount: 1

image: r.cfcr.io/codefresh-inc/codefresh/charts-manager
imageTag: master

# Service port
port: 9000

# Pod (target) port
targetPort: 9000

# service database name
mongodbName: charts-manager

mongoCreateDbJobScript: files/mongoCreateDbJobScript

# formatLogsToElk logs will be formatter as elk expect to read it
formatLogsToElk: true
