## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
imagePullPolicy: Always

# number of replicas
# by default 1
# replicaCount: 1

# image name
image: codefresh/cf-api

# image tag
imageTag: master

# port
port: 80

# internal port
internalPort: 3000

# mapping for internal port
targetInternalPort: 40000

# target port
targetPort: 80

# defualt mongo image to use for mongoimport
mongodbImage: bitnami/mongodb:3.4.5-r0

# GitHub configuration
github:
  apiHost: api.github.com
  # apiPathPrefix: /api/v3 (only for Enterprise GitHub)
  loginHost: github.com
  protocol: https

gitlab:
  loginHost: gitlab.com
  protocol: https

# Segment
segmentEnable: false

providersData: |
  {
    "aws": {}
  }

# Example of how to specify AWS credentials for API service
#awsCredentials:
#  awsAccessKeyId: aaa
#  awsSecretAccessKey: aaa

# Internal registry protocol
# internalRegistryProtocol: http

# Static ENV variables
env:
  ACTIVITY_LOG_URI: http://activity-log
  APP_ENV: kubernetes
  DOCKER_NODE_CERT_PATH: /etc/ssl/cf
  DOCKER_NODE_PUBLIC_DOMAIN: cf-cd.com
  #GOOGLE_KUBE_SERVICE_URI: http://cf-google-auth
  LOGGER_LEVEL: error
  LOGGER_MORGAN_ACTIVE: false
  LOGS_PATH: /var/log/cf-api.log
  MAIL_ACTIVE: true
  NODE_ENV: kubernetes
  OAUTH_ROUTER_CALLBACK: ""
  PROGRESS_BUILDLOGS_BUCKETNAME: ""
  PROVIDERS_JSON_PATH: /etc/admin/providers.json
  RUNTIME_ENVS_JSON_PATH: /etc/admin/runtimeEnvironments.json
