## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
imagePullPolicy: Always

# number of replicas
# by default 1
# replicaCount: 1

# image name
image: codefresh/payments

# image tag
imageTag: master

# exposed port
port: 9000

# application target port
targetPort: 9000
