## Enabling ingress controller
enabled: true

# number of replicas
# by default 1
# replicaCount: 1

# image name
image: google_containers/defaultbackend
dockerRegistry: gcr.io/

# image tag
imageTag: 1.3

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
imagePullPolicy: IfNotPresent

# Service type (ClusterIP, NodePort, LoadBalancer)
#backend service
#serviceType: ClusterIP

# Service type (ClusterIP, NodePort, LoadBalancer)
#controllerServiceType: LoadBalancer

# ports
livenessPort: 8080
containerPort: 8080
servicePort: 80

controllerImage: k8s.gcr.io/ingress-nginx/controller
controllerImageTag: v0.51.0

controllerContainerPort: 80
controllerHostPost: 80
controllerSecureContainerPort: 443
controllerSecureHostPort: 443
controllerProbePort: 10254

controller:
  ingressClassResource:
    enabled: true
    name: nginx-codefresh
    default: false
    controllerValue: "k8s.io/codefresh-ingress-nginx"
    parameters: {}
  labels: {}
  service:
    annotations: {}  
