---
# records to /etc/hosts of the containers
# hostsApp: default empty

runtime_envs:
  - name: codefresh-inc
    inCluster: true
    selectorRuntimeEnv: codefresh-inc
    namespace: dinds
  - name: cluster-dev-1
    clusterName: cluster-dev-1.cf-cd.com
    inCluster: true
    selectorRuntimeEnv: codefresh
    queueServer: tls://rt-queue-dev-1-load.cf-cd.com:4222
    tls:
      ca: /etc/ssl/cf/ca.pem
      cert: /etc/ssl/cf/cert.pem
      # !!! key must be last element (go template limitations)
      key: /etc/ssl/cf/key.pem