{{- if index .Values "argo-platform" "enabled" }}
{{- if .Values.webTLS }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.appUrl }}-cert
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.webTLS.cert | b64enc | quote }}
  tls.key: {{ .Values.webTLS.key | b64enc | quote }}
{{- end }}
{{- end }}