apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service  | quote }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
data:
  # app url
  app-url: {{ .Values.appUrl }}

  # default application protocol: http or https
  app-protocol: {{ .Values.appProtocol }}

  # segment black list users
  segment-blacklist-users: {{ default "" .Values.segmentBlackList }}

  # consul service
  consul-service: consul

  # PostresSQL service name
  postgres-service: postgresql
  # PostresSQL database
  postgres-database: {{ .Values.postgresql.postgresDatabase }}

  # Redis service
  redis-service: redis

  # Docker registry service
  registry-service: registry
  # Docker registry service port
  registry-service-port: "5000"

  # Payments service name
  payments-service: payments

  # Firebase url
  firebase-url: https://codefresh-on-prem.firebaseio.com/on-prem

  # CFCR
  cfcr-domain: {{ default "cfcr.staging.io" .Values.cfcrDomain }}

  # OAuth router callback
  oauth-router-callback: {{ default "http://codefresh-inc-3.cf-cd.com:2222/api/auth/github/callback/" .Values.oauthRouterCallback }}

  # GCE Project
  google-compute-engine-project: {{ default "savvy-badge-103912" .Values.gceProject }}