apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service  | quote }}
data:
  # segment black list users
  segment-blacklist-users: {{ default "" .Values.segmentBlackList | quote }}

  # Firebase url
  firebase-url: {{ .Values.firebaseUrl | quote }}

  # CFCR
  cfcr-domain: {{ default "cfcr.staging.io" .Values.cfcrDomain | quote }}

  # GCE Project
  google-compute-engine-project: {{ default "savvy-badge-103912" .Values.gceProject }}