# additional records to /etc/hosts of the containers
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-etc-hosts
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service  | quote }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
data:
  hosts-app: |
    {{ default "" .Values.hostsApp }}