# number of replicas
# by default 2
# replicaCount: 2

# image name
image: docker

# image tag  
imageTag: 17.05-dind

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
imagePullPolicy: IfNotPresent

# dind container port (1300 - default)
containerPort: 1300

# consul configuration (default: consul)
consulService: consul
# consul http port
consulHttpPort: 8500

# codefresh service name (chart name)
codefreshService: codefresh

# Codefresh APP URL
appUrl: app.codefresh.dev 