imagePullPolicy: Always
redeploy: false

# Number of replicas
replicaCount: 1

image: r.cfcr.io/codefresh-inc/codefresh/mailer
imageTag: master

# Service port
port: 80

# Pod (target) port
targetPort: 9000

# By default, the mailer service is disabled
active: ""

# Secrets, should be replaced with env specific values
sendgridKey: ""

