## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
imagePullPolicy: Always

# number of replicas
# by default 1
# replicaCount: 1

# image name
image: codefresh/cf-ui

# image tag  
imageTag: develop

# port 
port: 80

# ENV
env:
  NODE_ENV: kubernetes
  ASSETS_OPTIMIZED: "true"
  LOGGER_LEVEL: error
  LOGGER_MORAN_ACTIVE: "false"
  LOGS_PATH: /var/log/cf-ui.log
  NEW_USER_REDIRECT: ""

